// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbQhP3NC9LSC4sGqDz_YeQ7eBoEN00kc',
    appId: '1:226638631297:web:15d3082986fa1ca5395880',
    messagingSenderId: '226638631297',
    projectId: 'betting-pos',
    authDomain: 'betting-pos.firebaseapp.com',
    storageBucket: 'betting-pos.appspot.com',
    measurementId: 'G-F66BHW88M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_dEQ9dXlXKoKLZpQRKXIgZzbZBYWAgTg',
    appId: '1:226638631297:android:9850358cd7673206395880',
    messagingSenderId: '226638631297',
    projectId: 'betting-pos',
    storageBucket: 'betting-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADCa4ix7xShLBuC3hoHh2wda10yR0iZA4',
    appId: '1:226638631297:ios:fe01d1499a60263a395880',
    messagingSenderId: '226638631297',
    projectId: 'betting-pos',
    storageBucket: 'betting-pos.appspot.com',
    iosBundleId: 'com.example.betPos',
  );
}
